"""
================================================================================
FILE: bundle.py
MODULE: app/ml/export/
PURPOSE: Build a self-contained surrogate export ZIP bundle containing the
         fitted model, normalization params, an optional PCA transform, a
         ready-to-use surrogate.py wrapper, and a README.
MAINTAINER: Kalki Sharma (kalkijsharma@gmail.com)
CREATED: 2026-05-26
LAST MODIFIED: 2026-06-03
VERSION: 1.0.1
================================================================================
"""

# Copyright © 2026 Kalki Sharma. All rights reserved.

import io
import json
import zipfile
from datetime import datetime, timezone

import joblib
import sklearn

# ── surrogate.py wrapper template ────────────────────────────────────────────
# Uses <<<MARKER>>> substitution to avoid conflicts with Python brace syntax.

_SURROGATE_PY_TEMPLATE = '''\
"""
Surrogate model wrapper — generated by surrogate-toolkit v<<<TOOLKIT_VERSION>>>.
Dataset : <<<DATASET_NAME>>>
Exported: <<<EXPORTED_AT>>>

Input columns  (in order): <<<INPUT_COLUMNS>>>
Output columns (in order): <<<OUTPUT_COLUMNS>>>

Quick start::

    from surrogate import SurrogateModel
    import numpy as np

    sm = SurrogateModel()

    # numpy array — one row per sample, columns in the order listed above
    X = np.array([[<<<EXAMPLE_VALUES>>>]])
    y = sm.predict(X)   # shape (n_samples, <<<N_OUTPUTS>>>)

    # pandas DataFrame — column names are matched automatically
    import pandas as pd
    df = pd.DataFrame({<<<COLUMN_EXAMPLE>>>})
    y  = sm.predict(df)

Requirements: numpy, joblib, scikit-learn>=<<<SKLEARN_VERSION>>> (pandas optional)
"""
import json
import os

import numpy as np
import joblib

_HERE = os.path.dirname(os.path.abspath(__file__))


class SurrogateModel:
    """Wraps the exported surrogate and handles normalization internally."""

    def __init__(self):
        self._model = joblib.load(os.path.join(_HERE, "model.joblib"))
        with open(os.path.join(_HERE, "pipeline.json")) as fh:
            self._pipeline = json.load(fh)
        self._pca = None
        pca_path = os.path.join(_HERE, "pca.joblib")
        if os.path.exists(pca_path):
            self._pca = joblib.load(pca_path)

    @property
    def input_columns(self):
        return list(self._pipeline["input_columns"])

    @property
    def output_columns(self):
        return list(self._pipeline["output_columns"])

    def predict(self, X):
        """Return predictions for raw (unnormalized) inputs.

        Args:
            X: numpy array of shape (n_samples, n_inputs), or a pandas
               DataFrame with columns matching input_columns (order
               irrelevant for DataFrame; must match order for ndarray).

        Returns:
            numpy array of shape (n_samples, n_outputs).

        Raises:
            ValueError: Wrong number of columns or missing column names.
        """
        X_arr = self._coerce_input(X)
        X_norm = self._normalize(X_arr)
        if self._pca is not None:
            X_norm = self._pca.transform(X_norm)
        return self._model.predict(X_norm)

    # ── internals ─────────────────────────────────────────────────────────────

    def _coerce_input(self, X):
        expected = self._pipeline["input_columns"]
        try:
            import pandas as pd
            if isinstance(X, pd.DataFrame):
                missing = [c for c in expected if c not in X.columns]
                if missing:
                    raise ValueError(
                        f"DataFrame is missing columns: {missing}. "
                        f"Expected: {expected}"
                    )
                return X[expected].values.astype(float)
        except ImportError:
            pass
        arr = np.asarray(X, dtype=float)
        if arr.ndim == 1:
            arr = arr.reshape(1, -1)
        if arr.shape[1] != len(expected):
            raise ValueError(
                f"Expected {len(expected)} input columns, got {arr.shape[1]}. "
                f"Columns in order: {expected}"
            )
        return arr

    def _normalize(self, X):
        params = self._pipeline.get("norm_params", {})
        cols   = self._pipeline["input_columns"]
        X_out  = X.copy()
        for i, col in enumerate(cols):
            p = params.get(col)
            if not p:
                continue
            method = p.get("method", "none")
            if method == "minmax":
                rng = p["max"] - p["min"]
                X_out[:, i] = (X_out[:, i] - p["min"]) / rng if rng != 0 else 0.0
            elif method == "zscore":
                X_out[:, i] = (
                    (X_out[:, i] - p["mean"]) / p["std"]
                    if p["std"] != 0 else 0.0
                )
        return X_out
'''


def build_export_bundle(state):
    """Assemble an in-memory ZIP export bundle for the active surrogate.

    Args:
        state: Application STATE dict.

    Returns:
        (zip_bytes: bytes, filename: str)

    Raises:
        ValueError: No trained model in STATE.
    """
    from config.settings import VERSION

    models_dict = state["surrogate_sessions"]["primary"]["models"]
    model       = models_dict.get("trained")
    results     = models_dict.get("results")
    if model is None or results is None:
        raise ValueError("No trained model. Train a model in Step 9 — Model first.")

    primary     = state["datasets"]["primary"]
    meta        = primary.get("metadata") or {}
    norm_params = meta.get("normalization_params") or {}
    pca_info    = state["surrogate_sessions"]["primary"].get("pca")

    # If PCA was applied, expose original input columns to the user
    if pca_info:
        input_columns = list(pca_info["original_inputs"])
    else:
        input_columns = list(results["input_columns"])
    output_columns = list(results["output_columns"])

    now          = datetime.now(timezone.utc)
    timestamp    = now.strftime("%Y%m%d_%H%M%S")
    exported_at  = now.isoformat()
    dataset_name = results.get("source_filename") or "unknown"

    pipeline = {
        "input_columns":  input_columns,
        "output_columns": output_columns,
        "model_type":     results["model_type"],
        "norm_params":    norm_params,
        "has_pca":        pca_info is not None,
        "sklearn_version": sklearn.__version__,
        "toolkit_version": VERSION,
        "dataset_name":   dataset_name,
        "exported_at":    exported_at,
    }

    surrogate_src = _build_surrogate_py(
        input_columns, output_columns, dataset_name, exported_at, VERSION
    )
    readme = _build_readme(
        input_columns, output_columns, results["model_type"],
        dataset_name, exported_at, VERSION, pca_info is not None
    )

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        _write_joblib(zf, "model.joblib", model)
        zf.writestr("pipeline.json", json.dumps(pipeline, indent=2))
        if pca_info is not None:
            _write_joblib(zf, "pca.joblib", pca_info["model"])
        zf.writestr("surrogate.py", surrogate_src)
        zf.writestr("README.txt", readme)

    safe_name = dataset_name.replace(".csv", "").replace(" ", "_")
    zip_name  = f"surrogate_export_{safe_name}_{timestamp}.zip"
    return buf.getvalue(), zip_name


# ── private helpers ───────────────────────────────────────────────────────────

def _write_joblib(zf, arcname, obj):
    buf = io.BytesIO()
    joblib.dump(obj, buf)
    zf.writestr(arcname, buf.getvalue())


def _build_surrogate_py(input_cols, output_cols, dataset_name, exported_at, version):
    preview   = input_cols[:3]
    col_ex    = ", ".join(f'"{c}": [0.0]' for c in preview)
    if len(input_cols) > 3:
        col_ex += ", ..."

    return (
        _SURROGATE_PY_TEMPLATE
        .replace("<<<TOOLKIT_VERSION>>>", version)
        .replace("<<<DATASET_NAME>>>",    dataset_name)
        .replace("<<<EXPORTED_AT>>>",     exported_at)
        .replace("<<<INPUT_COLUMNS>>>",   str(input_cols))
        .replace("<<<OUTPUT_COLUMNS>>>",  str(output_cols))
        .replace("<<<EXAMPLE_VALUES>>>",  ", ".join(["0.0"] * len(input_cols)))
        .replace("<<<N_OUTPUTS>>>",       str(len(output_cols)))
        .replace("<<<COLUMN_EXAMPLE>>>",  col_ex)
        .replace("<<<SKLEARN_VERSION>>>", sklearn.__version__)
    )


def _build_readme(input_cols, output_cols, model_type, dataset_name,
                  exported_at, version, has_pca):
    lines = [
        "Surrogate Model Export",
        "=" * 40,
        f"Generated by surrogate-toolkit v{version}",
        f"Exported   : {exported_at}",
        f"Dataset    : {dataset_name}",
        f"Model type : {model_type}",
        f"sklearn    : {sklearn.__version__}",
        "",
        "FILES",
        "  model.joblib   — fitted surrogate model",
        "  pipeline.json  — normalization params + column metadata",
    ]
    if has_pca:
        lines.append("  pca.joblib     — PCA transform applied before prediction")
    lines += [
        "  surrogate.py   — Python wrapper (use this in your scripts)",
        "  README.txt     — this file",
        "",
        f"INPUT COLUMNS ({len(input_cols)}, pass in this order for ndarray input):",
    ]
    for i, c in enumerate(input_cols):
        lines.append(f"  [{i}]  {c}")
    lines += [
        "",
        f"OUTPUT COLUMNS ({len(output_cols)}):",
    ]
    for i, c in enumerate(output_cols):
        lines.append(f"  [{i}]  {c}")
    lines += [
        "",
        "QUICK START",
        "  from surrogate import SurrogateModel",
        "  import numpy as np",
        "",
        "  sm = SurrogateModel()",
        f"  X  = np.zeros((1, {len(input_cols)}))  # one sample, {len(input_cols)} inputs",
        "  y  = sm.predict(X)",
        f"  # y.shape == (1, {len(output_cols)})",
        "",
        "REQUIREMENTS",
        "  numpy",
        f"  scikit-learn>={sklearn.__version__}",
        "  joblib",
        "  pandas (optional — enables DataFrame input with named columns)",
    ]
    return "\n".join(lines)
