"""
================================================================================
FILE: numpy_bundle.py
MODULE: app/ml/export/
PURPOSE: Build a numpy-only surrogate export ZIP — no scikit-learn or joblib
         required at prediction time. Supported for Linear and GPR models.
         Uses a registry pattern so unsupported models/kernels fail loudly
         rather than silently producing wrong results.
MAINTAINER: Kalki Sharma (kalkijsharma@gmail.com)
CREATED: 2026-06-04
LAST MODIFIED: 2026-06-04
VERSION: 1.0.0
================================================================================
"""

# Copyright © 2026 Kalki Sharma. All rights reserved.

import io
import json
import zipfile
from datetime import datetime, timezone

import numpy as np
import sklearn

# ── Registry — update these when new models or kernels are added ──────────────

NUMPY_SUPPORTED_MODELS  = {"linear", "gpr"}
NUMPY_SUPPORTED_KERNELS = {"rbf", "matern15", "matern25", "rq"}

# ── Shared normalization block embedded in every surrogate.py ─────────────────

_NORM_BLOCK = '''
def _coerce(X, input_columns):
    try:
        import pandas as pd
        if isinstance(X, pd.DataFrame):
            missing = [c for c in input_columns if c not in X.columns]
            if missing:
                raise ValueError(f"DataFrame missing columns: {missing}. Expected: {input_columns}")
            return X[input_columns].values.astype(float)
    except ImportError:
        pass
    arr = np.asarray(X, dtype=float)
    if arr.ndim == 1:
        arr = arr.reshape(1, -1)
    if arr.shape[1] != len(input_columns):
        raise ValueError(
            f"Expected {len(input_columns)} input columns, got {arr.shape[1]}. "
            f"Columns in order: {input_columns}"
        )
    return arr


def _normalize(X, columns, params):
    X_out = X.copy()
    for i, col in enumerate(columns):
        p = params.get(col)
        if not p:
            continue
        m = p.get("method", "none")
        if m == "minmax":
            rng = p["max"] - p["min"]
            X_out[:, i] = (X_out[:, i] - p["min"]) / rng if rng != 0 else 0.0
        elif m == "zscore":
            X_out[:, i] = (X_out[:, i] - p["mean"]) / p["std"] if p["std"] != 0 else 0.0
        elif m == "log":
            shift = p.get("shift", 0.0)
            X_out[:, i] = np.log10(np.clip(X_out[:, i] + shift, 1e-12, None))
    return X_out
'''

# ── Linear surrogate.py template ──────────────────────────────────────────────

_LINEAR_TEMPLATE = '''\
"""
Surrogate model (numpy-only) — generated by surrogate-toolkit v<<<VERSION>>>.
Model type : linear (Ridge Regression)
Dataset    : <<<DATASET_NAME>>>
Exported   : <<<EXPORTED_AT>>>

Input columns  (in order): <<<INPUT_COLUMNS>>>
Output columns (in order): <<<OUTPUT_COLUMNS>>>

Quick start::

    from surrogate import SurrogateModel
    import numpy as np

    sm = SurrogateModel()
    X  = np.array([[<<<EXAMPLE_VALUES>>>]])   # one row, raw physical values
    y  = sm.predict(X)                        # shape (1, <<<N_OUTPUTS>>>)

    import pandas as pd
    df = pd.DataFrame(<<<DF_EXAMPLE>>>)
    y  = sm.predict(df)

Requirements: numpy (pandas optional)
"""
import numpy as np

_INPUT_COLUMNS  = <<<INPUT_COLUMNS>>>
_OUTPUT_COLUMNS = <<<OUTPUT_COLUMNS>>>
_NORM_PARAMS    = <<<NORM_PARAMS>>>
_COEF           = np.array(<<<COEF>>>)        # shape (n_outputs, n_inputs)
_INTERCEPT      = np.array(<<<INTERCEPT>>>)   # shape (n_outputs,)


class SurrogateModel:
    """Numpy-only Ridge regression surrogate wrapper."""

    @property
    def input_columns(self):  return list(_INPUT_COLUMNS)

    @property
    def output_columns(self): return list(_OUTPUT_COLUMNS)

    def predict(self, X):
        """Return predictions for raw (unnormalized) inputs.

        Args:
            X: numpy array (n_samples, n_inputs) or pandas DataFrame.
        Returns:
            numpy array (n_samples, n_outputs).
        """
        X_arr  = _coerce(X, _INPUT_COLUMNS)
        X_norm = _normalize(X_arr, _INPUT_COLUMNS, _NORM_PARAMS)
        return (X_norm @ _COEF.T) + _INTERCEPT  # (n_samples, n_outputs)

<<<NORM_BLOCK>>>
'''

# ── GPR surrogate.py template ─────────────────────────────────────────────────

_GPR_TEMPLATE = '''\
"""
Surrogate model (numpy-only) — generated by surrogate-toolkit v<<<VERSION>>>.
Model type : gpr (Gaussian Process Regression, <<<KERNEL_LABEL>>> kernel)
Dataset    : <<<DATASET_NAME>>>
Exported   : <<<EXPORTED_AT>>>

Input columns  (in order): <<<INPUT_COLUMNS>>>
Output columns (in order): <<<OUTPUT_COLUMNS>>>

Quick start::

    from surrogate import SurrogateModel
    import numpy as np

    sm = SurrogateModel()
    X  = np.array([[<<<EXAMPLE_VALUES>>>]])   # one row, raw physical values
    y  = sm.predict(X)                        # shape (1, <<<N_OUTPUTS>>>)

    import pandas as pd
    df = pd.DataFrame(<<<DF_EXAMPLE>>>)
    y  = sm.predict(df)

Files::
    X_train.npy  — normalized training inputs  (n_train, n_inputs)
    alpha.npy    — dual coefficients           (n_train, n_outputs)

Requirements: numpy (pandas optional)
"""
import os
import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))

_INPUT_COLUMNS  = <<<INPUT_COLUMNS>>>
_OUTPUT_COLUMNS = <<<OUTPUT_COLUMNS>>>
_NORM_PARAMS    = <<<NORM_PARAMS>>>
_KERNEL_PARAMS  = <<<KERNEL_PARAMS>>>   # name, length_scale, [rq_alpha]
_Y_TRAIN_MEAN   = np.array(<<<Y_TRAIN_MEAN>>>)  # shape (n_outputs,)
_Y_TRAIN_STD    = np.array(<<<Y_TRAIN_STD>>>)   # shape (n_outputs,)


class SurrogateModel:
    """Numpy-only GPR surrogate wrapper."""

    def __init__(self):
        self._X_train = np.load(os.path.join(_HERE, "X_train.npy"))  # (n_train, n_inputs)
        self._alpha   = np.load(os.path.join(_HERE, "alpha.npy"))    # (n_train, n_outputs)

    @property
    def input_columns(self):  return list(_INPUT_COLUMNS)

    @property
    def output_columns(self): return list(_OUTPUT_COLUMNS)

    def predict(self, X):
        """Return predictions for raw (unnormalized) inputs.

        Args:
            X: numpy array (n_samples, n_inputs) or pandas DataFrame.
        Returns:
            numpy array (n_samples, n_outputs).
        """
        X_arr  = _coerce(X, _INPUT_COLUMNS)
        X_norm = _normalize(X_arr, _INPUT_COLUMNS, _NORM_PARAMS)
        K      = _gpr_kernel(X_norm, self._X_train, _KERNEL_PARAMS)  # (n_samples, n_train)
        y_norm = K @ self._alpha                                       # (n_samples, n_outputs)
        return _Y_TRAIN_STD * y_norm + _Y_TRAIN_MEAN                   # denormalize


# ── GPR kernel (numpy implementation matching sklearn exactly) ─────────────────

def _gpr_kernel(X1, X2, params):
    """Compute the kernel matrix K(X1, X2) using the exported hyperparameters."""
    name = params["name"]
    diff = X1[:, None, :] - X2[None, :, :]  # (n1, n2, n_inputs)

    if name in ("rbf", "matern15", "matern25"):
        ls = np.asarray(params["length_scale"], dtype=float)
        scaled_sq = np.sum(diff ** 2 / ls ** 2, axis=-1)  # (n1, n2) — ARD

        if name == "rbf":
            return np.exp(-0.5 * scaled_sq)

        r = np.sqrt(np.maximum(scaled_sq, 0.0))
        if name == "matern15":
            sq3r = np.sqrt(3.0) * r
            return (1.0 + sq3r) * np.exp(-sq3r)
        # matern25
        sq5r = np.sqrt(5.0) * r
        return (1.0 + sq5r + sq5r ** 2 / 3.0) * np.exp(-sq5r)

    if name == "rq":
        ls      = float(params["length_scale"])
        rq_a    = float(params["rq_alpha"])
        d_sq    = np.sum(diff ** 2, axis=-1)
        return (1.0 + d_sq / (2.0 * rq_a * ls ** 2)) ** (-rq_a)

    raise ValueError(f"Unknown kernel: {name!r}")

<<<NORM_BLOCK>>>
'''


# ── Public entry point ────────────────────────────────────────────────────────

def build_numpy_export_bundle(state):
    """Build an in-memory numpy-only export ZIP for the active surrogate.

    Args:
        state: Application STATE dict.

    Returns:
        (zip_bytes: bytes, filename: str)

    Raises:
        ValueError: Model type or kernel not in NUMPY_SUPPORTED_* registries,
                    or no trained model in STATE.
    """
    from config.settings import VERSION

    models_dict = state["surrogate_sessions"]["primary"]["models"]
    model       = models_dict.get("trained")
    results     = models_dict.get("results")
    if model is None or results is None:
        raise ValueError("No trained model. Train a model in Step 9 — Model first.")

    model_type = results["model_type"]
    if model_type not in NUMPY_SUPPORTED_MODELS:
        raise ValueError(
            f"NumPy-only export is not available for '{model_type}'. "
            f"Supported: {sorted(NUMPY_SUPPORTED_MODELS)}. Use the standard export instead."
        )

    primary     = state["datasets"]["primary"]
    meta        = primary.get("metadata") or {}
    norm_params = meta.get("normalization_params") or {}
    pca_info    = state["surrogate_sessions"]["primary"].get("pca")

    input_columns  = list(pca_info["original_inputs"]) if pca_info else list(results["input_columns"])
    output_columns = list(results["output_columns"])
    dataset_name   = results.get("source_filename") or "unknown"

    now         = datetime.now(timezone.utc)
    timestamp   = now.strftime("%Y%m%d_%H%M%S")
    exported_at = now.isoformat()

    if model_type == "linear":
        zip_bytes = _build_linear(
            model, input_columns, output_columns,
            norm_params, dataset_name, exported_at, VERSION,
        )
    else:  # gpr
        kernel_name = getattr(model, "_kernel_name", "rbf")
        if kernel_name not in NUMPY_SUPPORTED_KERNELS:
            raise ValueError(
                f"NumPy-only export is not supported for GPR kernel '{kernel_name}'. "
                f"Supported kernels: {sorted(NUMPY_SUPPORTED_KERNELS)}."
            )
        zip_bytes = _build_gpr(
            model, input_columns, output_columns,
            norm_params, dataset_name, exported_at, VERSION,
        )

    safe_name = dataset_name.replace(".csv", "").replace(" ", "_")
    zip_name  = f"surrogate_numpy_{safe_name}_{timestamp}.zip"
    return zip_bytes, zip_name


# ── Linear builder ────────────────────────────────────────────────────────────

def _build_linear(model, input_columns, output_columns,
                  norm_params, dataset_name, exported_at, version):
    sklearn_model = model._model
    coef      = sklearn_model.coef_.tolist()       # (n_outputs, n_inputs)
    intercept = np.atleast_1d(sklearn_model.intercept_).tolist()  # (n_outputs,)

    src = _fill_linear_template(
        input_columns, output_columns, norm_params,
        coef, intercept, dataset_name, exported_at, version,
    )
    readme = _build_readme_linear(
        input_columns, output_columns, dataset_name, exported_at, version,
    )

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("surrogate.py", src)
        zf.writestr("README.txt",   readme)
    return buf.getvalue()


def _fill_linear_template(input_columns, output_columns, norm_params,
                           coef, intercept, dataset_name, exported_at, version):
    n_out   = len(output_columns)
    ex_vals = ", ".join(["0.0"] * len(input_columns))
    df_ex   = "{" + ", ".join(f'"{c}": [0.0]' for c in input_columns[:3])
    if len(input_columns) > 3:
        df_ex += ", ..."
    df_ex += "}"

    return (
        _LINEAR_TEMPLATE
        .replace("<<<VERSION>>>",        version)
        .replace("<<<DATASET_NAME>>>",   dataset_name)
        .replace("<<<EXPORTED_AT>>>",    exported_at)
        .replace("<<<INPUT_COLUMNS>>>",  json.dumps(input_columns))
        .replace("<<<OUTPUT_COLUMNS>>>", json.dumps(output_columns))
        .replace("<<<NORM_PARAMS>>>",    json.dumps(norm_params, indent=4))
        .replace("<<<COEF>>>",           json.dumps(coef))
        .replace("<<<INTERCEPT>>>",      json.dumps(intercept))
        .replace("<<<EXAMPLE_VALUES>>>", ex_vals)
        .replace("<<<N_OUTPUTS>>>",      str(n_out))
        .replace("<<<DF_EXAMPLE>>>",     df_ex)
        .replace("<<<NORM_BLOCK>>>",     _NORM_BLOCK)
    )


# ── GPR builder ───────────────────────────────────────────────────────────────

def _build_gpr(model, input_columns, output_columns,
               norm_params, dataset_name, exported_at, version):
    estimators = model._model.estimators_
    kernel_name = getattr(model, "_kernel_name", "rbf")

    # Stack arrays from per-output estimators
    X_train      = estimators[0].X_train_                                   # (n_train, n_inputs)
    alpha_matrix = np.column_stack([est.alpha_ for est in estimators])      # (n_train, n_outputs)
    y_train_mean = np.array([float(np.atleast_1d(est._y_train_mean)[0]) for est in estimators])
    y_train_std  = np.array([float(np.atleast_1d(est._y_train_std)[0])  for est in estimators])

    kernel_params = _extract_kernel_params(estimators[0].kernel_, kernel_name)

    src = _fill_gpr_template(
        input_columns, output_columns, norm_params,
        kernel_params, y_train_mean.tolist(), y_train_std.tolist(),
        dataset_name, exported_at, version,
    )
    readme = _build_readme_gpr(
        input_columns, output_columns, kernel_name, dataset_name,
        exported_at, version, X_train.shape[0],
    )

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("surrogate.py", src)
        zf.writestr("README.txt",   readme)
        zf.writestr("X_train.npy",  _npy_bytes(X_train))
        zf.writestr("alpha.npy",    _npy_bytes(alpha_matrix))
    return buf.getvalue()


def _extract_kernel_params(kernel, kernel_name):
    """Extract JSON-serializable kernel hyperparameters from a fitted sklearn kernel."""
    params = {"name": kernel_name}
    if kernel_name in ("rbf", "matern15", "matern25"):
        ls = kernel.length_scale
        params["length_scale"] = ls.tolist() if hasattr(ls, "tolist") else float(ls)
    elif kernel_name == "rq":
        params["length_scale"] = float(kernel.length_scale)
        params["rq_alpha"]     = float(kernel.alpha)
    return params


def _fill_gpr_template(input_columns, output_columns, norm_params,
                        kernel_params, y_train_mean, y_train_std,
                        dataset_name, exported_at, version):
    kernel_labels = {
        "rbf":      "RBF (ARD)",
        "matern15": "Matérn 1.5 (ARD)",
        "matern25": "Matérn 2.5 (ARD)",
        "rq":       "Rational Quadratic",
    }
    n_out   = len(output_columns)
    ex_vals = ", ".join(["0.0"] * len(input_columns))
    df_ex   = "{" + ", ".join(f'"{c}": [0.0]' for c in input_columns[:3])
    if len(input_columns) > 3:
        df_ex += ", ..."
    df_ex += "}"

    return (
        _GPR_TEMPLATE
        .replace("<<<VERSION>>>",        version)
        .replace("<<<KERNEL_LABEL>>>",   kernel_labels.get(kernel_params["name"], kernel_params["name"]))
        .replace("<<<DATASET_NAME>>>",   dataset_name)
        .replace("<<<EXPORTED_AT>>>",    exported_at)
        .replace("<<<INPUT_COLUMNS>>>",  json.dumps(input_columns))
        .replace("<<<OUTPUT_COLUMNS>>>", json.dumps(output_columns))
        .replace("<<<NORM_PARAMS>>>",    json.dumps(norm_params, indent=4))
        .replace("<<<KERNEL_PARAMS>>>",  json.dumps(kernel_params, indent=4))
        .replace("<<<Y_TRAIN_MEAN>>>",   json.dumps(y_train_mean))
        .replace("<<<Y_TRAIN_STD>>>",    json.dumps(y_train_std))
        .replace("<<<EXAMPLE_VALUES>>>", ex_vals)
        .replace("<<<N_OUTPUTS>>>",      str(n_out))
        .replace("<<<DF_EXAMPLE>>>",     df_ex)
        .replace("<<<NORM_BLOCK>>>",     _NORM_BLOCK)
    )


# ── README builders ───────────────────────────────────────────────────────────

def _build_readme_linear(input_columns, output_columns, dataset_name, exported_at, version):
    lines = [
        "Surrogate Model Export (NumPy-only)",
        "=" * 40,
        f"Generated by surrogate-toolkit v{version}",
        f"Exported   : {exported_at}",
        f"Dataset    : {dataset_name}",
        f"Model type : linear (Ridge Regression)",
        f"sklearn    : {sklearn.__version__} (not required at prediction time)",
        "",
        "FILES",
        "  surrogate.py   — self-contained Python wrapper (only file you need)",
        "  README.txt     — this file",
        "",
        "PREDICTION EQUATION",
        "  y = X_normalized @ coef.T + intercept",
        "  All normalization is handled internally — pass raw physical values.",
        "",
        f"INPUT COLUMNS ({len(input_columns)}, pass in this order for ndarray input):",
    ]
    for i, c in enumerate(input_columns):
        lines.append(f"  [{i}]  {c}")
    lines += ["", f"OUTPUT COLUMNS ({len(output_columns)}):"]
    for i, c in enumerate(output_columns):
        lines.append(f"  [{i}]  {c}")
    lines += [
        "",
        "QUICK START",
        "  from surrogate import SurrogateModel",
        "  import numpy as np",
        "",
        "  sm = SurrogateModel()",
        f"  X  = np.zeros((1, {len(input_columns)}))  # one sample, {len(input_columns)} inputs",
        "  y  = sm.predict(X)",
        f"  # y.shape == (1, {len(output_columns)})",
        "",
        "REQUIREMENTS",
        "  numpy",
        "  pandas (optional — enables DataFrame input with named columns)",
    ]
    return "\n".join(lines)


def _build_readme_gpr(input_columns, output_columns, kernel_name,
                       dataset_name, exported_at, version, n_train):
    kernel_labels = {
        "rbf": "RBF (ARD)", "matern15": "Matérn 1.5 (ARD)",
        "matern25": "Matérn 2.5 (ARD)", "rq": "Rational Quadratic",
    }
    lines = [
        "Surrogate Model Export (NumPy-only)",
        "=" * 40,
        f"Generated by surrogate-toolkit v{version}",
        f"Exported   : {exported_at}",
        f"Dataset    : {dataset_name}",
        f"Model type : gpr ({kernel_labels.get(kernel_name, kernel_name)} kernel)",
        f"n_train    : {n_train} rows",
        f"sklearn    : {sklearn.__version__} (not required at prediction time)",
        "",
        "FILES",
        "  surrogate.py   — Python wrapper with kernel math (only file you call)",
        "  X_train.npy    — normalized training inputs  (n_train, n_inputs)",
        "  alpha.npy      — dual coefficients            (n_train, n_outputs)",
        "  README.txt     — this file",
        "",
        "PREDICTION EQUATION",
        "  K = kernel(X_norm, X_train)     # (n_new, n_train)",
        "  y = K @ alpha * y_std + y_mean  # denormalize sklearn's normalize_y",
        "  All normalization and denormalization is handled internally.",
        "",
        f"INPUT COLUMNS ({len(input_columns)}, pass in this order for ndarray input):",
    ]
    for i, c in enumerate(input_columns):
        lines.append(f"  [{i}]  {c}")
    lines += ["", f"OUTPUT COLUMNS ({len(output_columns)}):"]
    for i, c in enumerate(output_columns):
        lines.append(f"  [{i}]  {c}")
    lines += [
        "",
        "QUICK START",
        "  from surrogate import SurrogateModel",
        "  import numpy as np",
        "",
        "  sm = SurrogateModel()",
        f"  X  = np.zeros((1, {len(input_columns)}))  # one sample, {len(input_columns)} inputs",
        "  y  = sm.predict(X)",
        f"  # y.shape == (1, {len(output_columns)})",
        "",
        "REQUIREMENTS",
        "  numpy",
        "  pandas (optional — enables DataFrame input with named columns)",
    ]
    return "\n".join(lines)


# ── Helper ────────────────────────────────────────────────────────────────────

def _npy_bytes(arr):
    """Serialize a numpy array to .npy format bytes."""
    buf = io.BytesIO()
    np.save(buf, arr)
    return buf.getvalue()
